### ISSUE TITLE
Can't create any memories

### ISSUE THREAD

**Issue by uskudarli** [Ali-Hakan/LivingHistory#32]
I tried to create memories several times. 
It fails.

There are also no memories shown. Maybe a DB access issue?

I tried:

![image](https://github.com/Ali-Hakan/LivingHistory/assets/1347035/c6ad0eb6-714e-4624-aa55-e215a00be978)

**Comment by Ali-Hakan** [comment]
Probably, sorry for the inconvenience. I am checking immediately.

uskudarli ***@***.***>, 14 Haz 2023 Çar, 02:12 tarihinde şunu
yazdı:

**Comment by Ali-Hakan** [comment]
I checked the problem, there seems to be a DB memory issue. I also solved the problem of not being able to search stories via advanced search section.
